name: gestion_produit
description: Une application pour gérer des produits et des catégories.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  provider: ^6.1.1          # Gestion d'état
  http: ^1.1.0              # Requêtes HTTP
  flutter_secure_storage: ^9.0.0  # Stockage sécurisé pour les tokens
  shared_preferences: ^2.2.1 # Stockage local
  cached_network_image: ^3.3.0  # Mise en cache des images
  flutter_form_builder: ^9.1.0  # Création de formulaires
  form_builder_validators: ^9.1.0  # Validation de formulaires
  animations: ^2.0.8       # Animations fluides
  infinite_scroll_pagination: ^4.0.0  # Pagination infinie
  flutter_dotenv: ^5.1.0   # Gestion des variables d'environnement
  intl: ^0.18.1            # Internationalisation
  another_flushbar: ^1.12.30  # Notifications élégantes
  shimmer: ^3.0.0          # Effet de chargement des images

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - .env