name: gestion_produit
description: Une application pour gérer des produits et des catégories.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  provider: ^6.1.2          # Gestion d'état
  http: ^1.3.0              # Requêtes HTTP
  flutter_secure_storage: ^9.2.4  # Stockage sécurisé pour les tokens
  shared_preferences: ^2.5.2 # Stockage local
  cached_network_image: ^3.4.1  # Mise en cache des images
  flutter_form_builder: ^10.0.1  # Création de formulaires
  form_builder_validators: ^11.1.2  # Validation de formulaires
  animations: ^2.0.11       # Animations fluides
  infinite_scroll_pagination: ^5.0.0  # Pagination infinie
  flutter_dotenv: ^5.2.1   # Gestion des variables d'environnement
  intl: ^0.19.0            # Internationalisation
  another_flushbar: ^1.12.30  # Notifications élégantes
  shimmer: ^3.0.0          # Effet de chargement des images

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.4.4
  build_runner: ^2.4.8
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    
    - .env